image: "rust:latest"

variables:
  GIT_STRATEGY: clone
  RUST_BACKTRACE: 1
  CARGO_INCREMENTAL: 0

before_script:
  - apt-get update -yqq
  - apt-get install -yqq --no-install-recommends build-essential git
  - rustup toolchain add $toolchain
  - rustup default $toolchain

stages:
  - checkfmt
  - test

checkfmt:rustfmt:
  stage: checkfmt
  variables:
    toolchain: stable
  script:
    - rustup component add rustfmt --toolchain $toolchain
    - cargo fmt --all -- --check

.test:
  stage: test
  script:
    - rustc --version && cargo --version  # Print version info for debugging
    - cargo build --verbose --all --examples --tests --benches --features "$features"
    - cargo test --all --verbose --features "$FEATURES"

test:stable:
  extends: .test
  variables:
    toolchain: stable
    features: curve25519-dalek serde

test:nightly:
  extends: .test
  variables:
    toolchain: nightly
    features: curve25519-dalek serde nightly

