language: rust
cache: cargo

# before_install:
#   - rustup component add rustfmt
#   - rustup component add clippy

matrix:
  include:
    - rust: stable
      env:
        - FEATURES=
    - rust: nightly
      env:
        - FEATURES='--all-features'
script:
  - |
    cargo build --verbose --all --examples --tests --benches $FEATURES &&
    cargo test --all --verbose $FEATURES # &&
    # cargo fmt --all -- --check
    # cargo clippy --all -- -D all
