language: rust
rust:
  - stable
  - nightly
script:
  - cargo build --verbose --all
  - cargo test --verbose --all
  - cargo build --verbose --all --all-features
  - cargo test --verbose --all --all-features
