[package]
name = "twopac"
version = "0.1.0"
authors = ["Alex J. Malozemoff <amaloz@galois.com>"]
license = "MIT"
readme = "README.md"
description = "A library for secure two-party computation"
categories = ["cryptography"]
keywords = ["cryptography", "secure-computation", "2PC"]
edition = "2018"
publish = false

[lib]

[features]
nightly = ["rand/nightly", "scuttlebutt/nightly", "ocelot/nightly", "fancy-garbling/nightly"]

[dependencies]
fancy-garbling = { path = "../fancy-garbling" }
ocelot = { git = "https://github.com/amaloz/ocelot" }
rand = "0.6"
scuttlebutt = { git = "https://github.com/amaloz/scuttlebutt" }

[dev-dependencies]
criterion = "0.2"

[profile.release]
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false

[profile.dev]
opt-level = 0
debug = true
debug-assertions = true
overflow-checks = true

[profile.bench]
opt-level = 3
debug = true
debug-assertions = true
overflow-checks = true

[[bench]]
name = "semihonest"
harness = false
