[package]
name = "twopac"
version = "0.1.0"
authors = ["Alex J. Malozemoff <amaloz@galois.com>"]
license = "MIT"
readme = "README.md"
description = "A library for secure two-party computation"
categories = ["cryptography"]
keywords = ["cryptography", "secure-computation", "2PC"]
edition = "2018"

[lib]

[features]
nightly = ["rand/nightly", "scuttlebutt/nightly", "ocelot/nightly", "fancy_garbling/nightly"]

[dependencies]
fancy_garbling = { path = "../fancy-garbling" }
ocelot = { git = "https://github.com/amaloz/ocelot" }
rand = "*"
scuttlebutt = { git = "https://github.com/amaloz/scuttlebutt" }

[dev-dependencies]
itertools = "*"

[profile.release]
debug = true
