[package]
name = "fancy_garbling"
version = "0.1.0"
authors = ["Brent Carmer <carmerb@eecs.oregonstate.edu>"]
build = "build.rs"
autobenches = false
edition = "2018"

[lib]
doctest = false

[build-dependencies]
cc = "1.0.28"

[dependencies]
base_conversion = { path = "base_conversion" }
bincode = { version = "1.0.1", features = ["i128"] } 
failure = "0.1.5"
itertools = "0.8.0"
libc = "0.2.47"
num = "0.2.0"
rand = "0.6.4"
serde = "1.0.85"
serde_derive = "1.0.85"
serde_json = "1.0.36"
time = "0.1.42"
pbr = "1.0.1"
crossbeam = "0.6.0"

[dev-dependencies]
criterion = "0.2.8"

[profile.release]
debug = true

[[bench]]
name = "wire_operations"
harness = false

[[bench]]
name = "garbling"
harness = false

[[bench]]
name = "parallel"
harness = false

[[bench]]
name = "thread"
harness = false
