[package]
name = "popsicle"
version = "0.1.0"
authors = ["Alex J. Malozemoff <amaloz@galois.com>"]
license = "MIT"
readme = "README.md"
description = "A library for private set intersection protocols"
categories = ["cryptography"]
keywords = ["cryptography", "private-set-intersection", "PSI"]
edition = "2018"

[lib]

[features]
nightly = ["rand/nightly", "scuttlebutt/nightly"]

[dependencies]
ocelot = { path = "../ocelot", features = ["unstable"] }
rand = "*"
rand_core = "*"
scuttlebutt = { path = "../scuttlebutt"}

[dev-dependencies]
criterion = "*"

[profile.release]
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false

[profile.dev]
opt-level = 0
debug = true
debug-assertions = true
overflow-checks = true

[profile.bench]
opt-level = 3
debug = true
debug-assertions = false
overflow-checks = false


[[bench]]
name = "psi"
harness = false
