[package]
name = "fancy_garbling"
version = "0.1.0"
authors = ["Brent Carmer <carmerb@eecs.oregonstate.edu>"]
build = "build.rs"
autobenches = false

[lib]
doctest = false

[build-dependencies]
cc = "^1.0"

[dependencies]
rand = "^0.3.14"
libc = "^0.2.0"
num = "^0.2"
num-traits = "^0.2.6"
base_conversion = { path = "base_conversion" }

[dev-dependencies]
criterion = "0.2"

# [profile.release]
# debug = true

[[bin]]
name = "dinn"
path = "apps/dinn.rs"

[[bench]]
name = "wire_operations"
harness = false

[[bench]]
name = "garbling"
harness = false

[[bench]]
name = "high_level"
harness = false
