[package]
name = "scuttlebutt"
version = "0.1.0"
authors = ["Alex J. Malozemoff <amaloz@galois.com>"]
license = "MIT"
readme = "README.md"
description = "A library of useful multi-party computation utilities"
keywords = ["cryptography", "MPC", "secure-computation"]
categories = ["cryptography"]
edition = "2018"
publish = false

[lib]

[features]
nightly = ["curve25519-dalek/simd_backend", "rand/nightly"]

[dependencies]
arrayref = "0.3"
curve25519-dalek = { version = "1.1", features = ["std"], optional = true }
failure = "0.1"
rand = "0.6"
rand_core = "0.4"
serde = { version = "1", features = ["derive"], optional = true }

[dev-dependencies]
criterion = "0.2"

[profile.release]
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false

[profile.dev]
opt-level = 0
debug = true
debug-assertions = true
overflow-checks = true

[profile.bench]
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false

[[bench]]
name = "bench"
harness = false