[package]
name = "ocelot"
version = "0.1.0"
authors = ["Alex J. Malozemoff <amaloz@galois.com>"]
edition = "2018"
autobenches = false

[lib]

[dependencies]
aesni = "*"
arrayref = "*"
bitvec = { git = "https://github.com/myrrlyn/bitvec" }
failure = "*"
itertools = "*"
curve25519-dalek = "*"
rand = "*"

[dev-dependencies]
criterion = "*"

[profile.release]
debug = true

[[bench]]
name = "bench"
harness = false