[package]
name = "ocelot"
version = "0.1.0"
authors = ["Alex J. Malozemoff <amaloz@galois.com>"]
edition = "2018"

[lib]

[dependencies]
aesni = "0.6.0"
arrayref = "0.3.5"
curve25519-dalek = "1"
rand = "0.6.1"