[package]
name = "ocelot"
version = "0.1.0"
authors = ["Alex J. Malozemoff <amaloz@galois.com>"]
edition = "2018"
autobenches = false

[lib]

[dependencies]
aesni = "0.6.0"
arrayref = "0.3"
bitvec = { git = "https://github.com/myrrlyn/bitvec" }
failure = "0.1"
itertools = "0.8"
curve25519-dalek = "1"
rand = "0.6"

[dev-dependencies]
criterion = "0.2"

[profile.release]
debug = true

[[bench]]
name = "bench"
harness = false