[package]
name = "fancy_garbling"
version = "0.1.0"
authors = ["Brent Carmer <carmerb@eecs.oregonstate.edu>"]
build = "build.rs"
autobenches = false
edition = "2018"

[lib]
doctest = false

[build-dependencies]
cc = "^1.0"

[dependencies]
base_conversion = { path = "base_conversion" }
rand = "^0.3.14"
libc = "^0.2.0"
num = "^0.2"
num-traits = "^0.2.6"
itertools = "^0.7.8"

[dev-dependencies]
criterion = "0.2.5"

[profile.release]
debug = true

[[bin]]
name = "profile"
path = "apps/profile.rs"

[[bench]]
name = "wire_operations"
harness = false

[[bench]]
name = "garbling"
harness = false

[[bench]]
name = "crt"
harness = false
