[package]
name = "fancy_garbling"
version = "0.1.0"
authors = ["Brent Carmer <carmerb@eecs.oregonstate.edu>"]
build = "build.rs"
autobenches = false

[build-dependencies]
cc = "^1.0"

[dependencies]
rand = "^0.3.14"
libc = "^0.2.0"
rust-gmp = "^0.5.0"
getopts = "^0.2"
base_conversion = { path = "base_conversion" }

[dev-dependencies]
criterion = "0.2"

[[bin]]
name = "benchmark"
path = "apps/benchmark.rs"

[[bench]]
name = "wire_operations"
harness = false
