[package]
name = "popsicle"
version = "0.3.0"
authors = ["Alex J. Malozemoff <amaloz@galois.com>"]
license = "MIT"
readme = "README.md"
description = "A library for private set intersection"
categories = ["cryptography"]
keywords = ["cryptography", "private-set-intersection", "PSI"]
edition = "2018"

[lib]

[features]
nightly = ["rand/nightly", "scuttlebutt/nightly", "ocelot/nightly", "ocelot/nightly"]
unstable = ["ocelot/unstable"]

[dependencies]
fancy-garbling = { git = "https://github.com/spaceships/fancy-garbling", tag = "0.3.0" }
itertools = "0.8.0"
ocelot = { git = "https://github.com/amaloz/ocelot", tag = "0.3.0" }
rand = "0.6.5"
scuttlebutt = { git = "https://github.com/amaloz/scuttlebutt", tag = "0.3.0" }
sha2 = "0.8.0"
twopac = { path = "../twopac" }

[dev-dependencies]
criterion = "0.2.11"

[profile.release]
opt-level = 3
debug = true
debug-assertions = false
overflow-checks = false

[profile.dev]
opt-level = 0
debug = false
debug-assertions = false
overflow-checks = false

[profile.bench]
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false

[[bench]]
name = "psz"
harness = false

[[bench]]
name = "psty"
harness = false
required-features = ["unstable"]

[[example]]
name = "psty"
harness = false
required-features = ["unstable"]
