[package]
name = "fancy_garbling"
version = "0.1.0"
authors = ["Brent Carmer <carmerb@eecs.oregonstate.edu>"]
build = "build.rs"
autobenches = false
edition = "2018"

[lib]
doctest = false

[build-dependencies]
cc = "1.0.29"

[dependencies]
base_conversion = { path = "base_conversion" }
crossbeam = "0.7.1"
itertools = "0.8.0"
libc = "0.2.49"
num = "0.2.0"
rand = "0.6.5"
scuttlebutt = { path = "../scuttlebutt", default-features = false, features = ["serde"] }
serde = { version = "1.0.88", features = ["derive"] }

[dev-dependencies]
criterion = "0.2.10"

[profile.release]
debug = true

[[bench]]
name = "wire_operations"
harness = false

[[bench]]
name = "garbling"
harness = false

[[bench]]
name = "parallel"
harness = false

[[bench]]
name = "rust"
harness = false
