[package]
name = "twopac"
version = "0.1.0"
authors = ["Alex J. Malozemoff <amaloz@galois.com>"]
edition = "2018"

[lib]

[dependencies]
failure = "*"
fancy_garbling = { git = "https://github.com/spaceships/fancy-garbling" }
# fancy_garbling = { path = "../fancy-garbling" }
ocelot = { path = "../ocelot" }
rand = "*"

[dev-dependencies]
# crossbeam = "*"
itertools = "*"

[profile.release]
debug = true
