[package]
name = "fancy_garbling"
version = "0.1.0"
authors = ["Brent Carmer <carmerb@eecs.oregonstate.edu>"]
build = "build.rs"
autobenches = false
edition = "2018"

[lib]
doctest = false

[build-dependencies]
cc = "1.0.26"

[dependencies]
base_conversion = { path = "base_conversion" }
rand = "0.6.1"
libc = "0.2.45"
num = "0.2.0"
num-traits = "0.2.6"
itertools = "0.8.0"
serde = "1.0.82"
serde_json = "1.0.33"
serde_derive = "1.0.82"

[dev-dependencies]
criterion = "0.2.5"

[profile.release]
debug = true

[[bin]]
name = "profile"
path = "apps/profile.rs"

[[bench]]
name = "wire_operations"
harness = false

[[bench]]
name = "garbling"
harness = false

[[bench]]
name = "crt"
harness = false
