[package]
name = "popsicle"
version = "0.1.0"
authors = ["Alex J. Malozemoff <amaloz@galois.com>"]
license = "MIT"
readme = "README.md"
description = "A library for private set intersection protocols"
categories = ["cryptography"]
keywords = ["cryptography", "private-set-intersection", "PSI"]
edition = "2018"

[lib]

[features]
nightly = ["rand/nightly", "scuttlebutt/nightly", "ocelot/nightly"]

[dependencies]
arrayref = "*"
ocelot = { git = "https://github.com/amaloz/ocelot", features = ["unstable"] }
rand = "*"
rand_core = "*"
scuttlebutt = { git = "https://github.com/amaloz/scuttlebutt"}
sha2 = "*"

[dev-dependencies]
criterion = "*"

[profile.release]
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false

[profile.dev]
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false

[profile.bench]
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false

[[bench]]
name = "psi"
harness = false
