[package]
name = "fancy-garbling"
version = "0.3.1"
authors = ["Brent Carmer <bcarmer@galois.com>"]
license = "MIT"
readme = "README.md"
description = "A library for boolean and arithmetic garbling"
categories = ["cryptography"]
keywords = ["cryptography", "garbled-circuit", "GC"]
edition = "2018"
autobenches = false
publish = false

[lib]
doctest = false

[features]
nightly = ["rand/nightly", "scuttlebutt/nightly"]

[dependencies]
base_conversion = { path = "base_conversion" }
itertools = "0.8.0"
rand = "0.6.5"
regex = "1.1.6"
scuttlebutt = { git = "https://github.com/amaloz/scuttlebutt", branch = "dev" }

[dev-dependencies]
criterion = "0.2.11"
crossbeam = "0.7.1"

[profile.release]
opt-level = 3
debug = true
debug-assertions = false
overflow-checks = false

[profile.dev]
opt-level = 0
debug = true
debug-assertions = true
overflow-checks = true

[profile.bench]
opt-level = 3
debug = true
debug-assertions = false
overflow-checks = false

[[bench]]
name = "wire_operations"
harness = false

[[bench]]
name = "garbling"
harness = false

[[bench]]
name = "circuits"
harness = false

[[bench]]
name = "util"
harness = false
