[package]
name = "ocelot"
version = "0.1.0"
authors = ["Alex J. Malozemoff <amaloz@galois.com>"]
build = "build.rs"
edition = "2018"
autobenches = false

[lib]

[dependencies]
aesni = "*"
arrayref = "*"
curve25519-dalek = { version = "*", features = ["std", "avx2_backend"] }
failure = "*"
itertools = "*"
libc = "*"
rand = { version = "*", features = ["nightly"] }

[build-dependencies]
cc = "*"

[dev-dependencies]
criterion = "*"

[profile.release]
debug = true

[profile.bench]
debug = true

[[bench]]
name = "utils"
harness = false

# [[bench]]
# name = "ot"
# harness = false
