[package]
name = "ocelot"
version = "0.1.0"
authors = ["Alex J. Malozemoff <amaloz@galois.com>"]
license = "MIT"
readme = "README.md"
description = "A library for oblivious transfer protocols"
categories = ["cryptography"]
keywords = ["cryptography", "oblivious-transfer", "OT"]
edition = "2018"
publish = false
build = "build.rs"

[lib]

[features]
nightly = ["curve25519-dalek/simd_backend", "rand/nightly", "scuttlebutt/nightly"]
unstable = []

[dependencies]
arrayref = "0.3"
curve25519-dalek = { version = "1.1", features = ["std"] }
libc = "*"
rand = "0.6"
rand_core = "0.4"
scuttlebutt = { git = "https://github.com/amaloz/scuttlebutt", features = ["curve25519-dalek"] }

[build-dependencies]
cc = "*"

[dev-dependencies]
criterion = "*"

[profile.release]
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false

[profile.dev]
opt-level = 0
debug = true
debug-assertions = true
overflow-checks = true

[profile.bench]
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false

[[bench]]
name = "ot"
harness = false

[[bench]]
name = "oprf"
harness = false
