[package]
name = "twopac"
version = "0.3.0"
authors = ["Alex J. Malozemoff <amaloz@galois.com>"]
license = "MIT"
readme = "README.md"
description = "A library for secure two-party computation"
categories = ["cryptography"]
keywords = ["cryptography", "secure-computation", "2PC"]
edition = "2018"
publish = false

[lib]

[features]
nightly = ["rand/nightly", "scuttlebutt/nightly", "ocelot/nightly", "fancy-garbling/nightly"]
unstable = []

[dependencies]
fancy-garbling = { git = "https://github.com/GaloisInc/fancy-garbling", branch = "dev" }
ocelot = { git = "https://github.com/GaloisInc/ocelot", branch = "dev" }
scuttlebutt = { git = "https://github.com/GaloisInc/scuttlebutt", branch = "dev" }
rand = "0.6"

[dev-dependencies]
criterion = "0.2"
itertools = "0.8"

[profile.release]
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false

[profile.dev]
opt-level = 0
debug = true
debug-assertions = true
overflow-checks = true

[profile.bench]
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false

[[bench]]
name = "semihonest"
harness = false
