[package]
name = "popsicle"
version = "0.3.0"
authors = ["Alex J. Malozemoff <amaloz@galois.com>"]
license = "MIT"
readme = "README.md"
description = "A library for private set intersection"
categories = ["cryptography"]
keywords = ["cryptography", "private-set-intersection", "PSI"]
edition = "2018"
publish = false

[lib]

[features]
nightly = ["rand/nightly", "scuttlebutt/nightly", "ocelot/nightly", "ocelot/nightly"]

[dependencies]
fancy-garbling = { path = "../fancy-garbling" }
ocelot         = { path = "../ocelot" }
scuttlebutt    = { path = "../scuttlebutt" }
twopac         = { path  = "../twopac" }
itertools      = "0.8.0"
rand           = "0.6.5"
openssl        = "0.10.23"
sha2           = "0.8.0"

[dev-dependencies]
criterion  = "0.2.11"
clap       = "2.33.0"
serde      = { version = "1.0.92", features = ["derive"] }
serde_yaml = "0.8.9"
rustyline  = "5.0.0"
pbr        = "1.0.1"
ascii      = "0.9.2"

[[bench]]
name = "psz"
harness = false

[[bench]]
name = "psty"
harness = false

[[example]]
name = "psty-payload"
harness = false

[[example]]
name = "secretsister"
harness = false
