[package]
name = "popsicle"
version = "0.4.0"
authors = ["Alex J. Malozemoff <amaloz@galois.com>"]
license = "MIT"
readme = "README.md"
description = "A library for private set intersection"
categories = ["cryptography"]
keywords = ["cryptography", "private-set-intersection", "PSI"]
edition = "2018"
publish = false

[lib]

[features]
nightly = ["rand/nightly", "scuttlebutt/nightly", "ocelot/nightly", "ocelot/nightly"]
psty = ["fancy-garbling", "openssl"]
serde1 = ["serde", "serde_json", "fancy-garbling/serde1"]

[dependencies]
ocelot         = { path = "../ocelot" }
scuttlebutt    = { path = "../scuttlebutt",  features = ["serde1"]}
itertools      = "0.8"
rand           = "0.7"
sha2           = "0.8"
serde          = {version = "1.0.117", features = ["derive"], optional = true }
serde_json     = {version = "1.0.59", optional = true }
fancy-garbling = { path = "../fancy-garbling", features = ["serde1"], optional = true }
openssl        = { version = "0.10.28", optional = true }

[dev-dependencies]
criterion  = "0.2.11"
clap       = "2.33.0"
serde      = { version = "1.0.92", features = ["derive"] }
serde_yaml = "0.8.9"
rustyline  = "5.0.0"
pbr        = "1.0.1"
ascii      = "0.9.2"

[[bench]]
name = "psz"
harness = false

[[bench]]
name = "psty"
harness = false
required-features = ["psty"]

[[example]]
name = "psty"
required-features = ["psty"]

[[example]]
name = "psty-payload"
required-features = ["psty"]

[[example]]
name = "secretsister"
required-features = ["psty"]

[[example]]
name = "match-compute"
required-features = ["psty"]

[[example]]
name = "client"
path = "examples/match-compute-sockets/client.rs"
required-features = ["psty"]

[[example]]
name = "server"
path = "examples/match-compute-sockets/server.rs"
required-features = ["psty"]

[[example]]
name = "prepare_files_server"
path = "examples/match-compute-parallel/server/prepare_files_server.rs"
required-features = ["psty", "serde1"]

[[example]]
name = "prepare_files_client"
path = "examples/match-compute-parallel/client/prepare_files_client.rs"
required-features = ["psty", "serde1"]

[[example]]
name = "server_thread"
path = "examples/match-compute-parallel/server/server_thread.rs"
required-features = ["psty", "serde1"]

[[example]]
name = "client_thread"
path = "examples/match-compute-parallel/client/client_thread.rs"
required-features = ["psty", "serde1"]

[[example]]
name = "join_aggregates_server"
path = "examples/match-compute-parallel/server/join_aggregates_server.rs"
required-features = ["psty", "serde1"]

[[example]]
name = "join_aggregates_client"
path = "examples/match-compute-parallel/client/join_aggregates_client.rs"
required-features = ["psty", "serde1"]
