[package]
authors = ["Alex J. Malozemoff <amaloz@galois.com>"]
autoexamples = true
build = "build.rs"
categories = ["cryptography"]
description = "A library for oblivious transfer protocols"
edition = "2018"
keywords = ["cryptography", "oblivious-transfer", "OT"]
license = "MIT"
name = "ocelot"
publish = false
readme = "README.md"
version = "0.4.0"

[lib]

[features]
nightly = ["rand/nightly", "scuttlebutt/nightly"]

[dependencies]
curve25519-dalek = {version = "2", features = ["std"]}
libc = "0.2"
log = "0.4"
rand = "0.7"
scuttlebutt = {path = "../scuttlebutt", features = ["curve25519-dalek"]}
sha2 = "0.9"
simple_logger = "1.12"
lazy_static = "1.4"
itertools = "0.10"

[build-dependencies]
cc = "1.0"

[dev-dependencies]
criterion = "0.2"

[[bench]]
harness = false
name = "ot"

[[bench]]
harness = false
name = "oprf"

[[example]]
harness = false
name = "kmprt"
