[package]
authors = ["Alex J. Malozemoff <amaloz@galois.com>"]
categories = ["cryptography"]
description = "A library of useful multi-party computation utilities"
edition = "2018"
keywords = ["cryptography", "MPC", "secure-computation"]
license = "MIT"
name = "scuttlebutt"
publish = false
readme = "README.md"
version = "0.4.0"

[lib]

[features]
nightly = ["rand/nightly"]
serde1 = ["serde"]
unstable = []

[dependencies]
curve25519-dalek = {version = "2", features = ["std"], optional = true}
rand = "0.7"
rand_core = "0.5"
crunchy = "0.2"
primitive-types = "0.10.1"
u256-literal = "1.1.0"
uint = "0.9.1"
serde = {version = "1", features = ["derive"], optional = true}
sha2 = "0.8"

[dev-dependencies]
criterion = "0.2"
hex = "0.3"

[[bench]]
harness = false
name = "aes128"

[[bench]]
harness = false
name = "aes256"

[[bench]]
harness = false
name = "block"

[[bench]]
harness = false
name = "block512"

[[bench]]
harness = false
name = "commitment"

[[bench]]
harness = false
name = "hash_aes"

[[bench]]
harness = false
name = "rand_aes"

[[bench]]
harness = false
name = "z2r"
